### ISSUE TITLE
[TC_AUTHOR_SUMAC_2] Course Data Researchers unable to log into Superset

### ISSUE THREAD

**Issue by pomegranited** [openedx/openedx-aspects#295]
Users with these roles should be able to login to Superset and see their course data: Course Admin, Course Staff, Limited Staff, Course Data Researcher

This works for all of these roles except for Course Data Researcher -- Superset doesn't allow login for this user type.

Note for testing: if you're changing a user's roles, you'll need to log them out completely from Open edX and log back in to fully test the role change.

**Comment by crathbun428** [comment]
@pomegranited - Thank you for catching! After chatting with Sara and Brian about this, I think this is actually OK for the time being. We'll see if the community ends up needing broader access for the role, but for this release we've decided to err on the side of restricting this user's access to embedded dashboards only for now. I can add a note to the testing spreadsheet, so that I can remember to update the wording on this test for future releases!
