### ISSUE TITLE
Superset charts: show course title instead of ID

### ISSUE THREAD

**Issue by pomegranited** [openedx/openedx-aspects#41]
https://github.com/openedx/tutor-contrib-oars/pull/3 added a basic Dashboard with course and block ID filters that apply to the charts inside.

But course IDs (and block IDs) are not user-friendly. Can we show Course Titles and Block display names instead, in the filters and on the charts?

**Investigations / Questions / Blockers**

* The course name/title is deeply nested into the event JSON: `tupleElement(tupleElement(tupleElement(event.context.contextActivities.parent, 1)[1], 'name'), 'en-US')`

   Can we pull this value out into a field using the clickhouse materialized view?
* Superset does not yet support using a "label" field when showing filter values in Dashboards: https://github.com/apache/superset/discussions/19184

  So if we want to show the Course Title in the Dashboard filters but send the Course ID to the chart's dimensions filter, then we'll need  this issue to be resolved.

**Comment by pomegranited** [comment]
FYI @bmtcril -- showing course titles isn't very easy yet :(

Also I couldn't figure out how to get this to appear on the [OARS Milestone: Reference Implementation for OARS V.1 (by epic)](https://github.com/orgs/openedx/projects/5/views/4) task list?

**Comment by bmtcril** [comment]
The native filters work seems to be progressing, maybe complete enough for us to turn on the feature flags? I'm watching the issue here, which is down to one last migration task that we may not need: https://github.com/apache/superset/issues/14383 

This won't show up on the milestone because it's not an epic, though we probably could add this to an existing epic or create a new one for all of the v1 Superset enhancements / fixes.

**Comment by bmtcril** [comment]
This should be sorted as part of https://github.com/openedx/tutor-contrib-aspects/pull/134 it's probably not perfect, but we can iterate in specific areas.
